Discord:
  Bot-token: "your-bot-token"
  activity:
    type: "playing"
    message: "Velocity Server"

netty:
  port: 8080

debug: false
forwarding-secret-file: "secret.complete.code"

view_connected_banned_ip: false